### ISSUE TITLE
Figure out how to handle automatic deployments of the site

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble-www#8]
Once a commit or PR has been landed in master, the site should automatically update.
If we need to clear any caches, we should be able to do so, too.

**Comment by Kissaki** [comment]
https://gitlab.com/mumble-voip/mumble-www/merge_requests/1

**Comment by Kissaki** [comment]
Can we move mumble-www to gitlab? staging and merge request review instances are working, and I know at least merge request review workflow is better on gitlab because it retains comments even after force pushing. So I'd rather drop github for new repos/this repo and move to gitlab.

Dunno how we'd autodeploy on github. Or we could still use gitlab for CI and deploy, even with a github master repo, but would not have automatic integration into the PR/merge workflow.

**Comment by Kissaki** [comment]
On IRC @mkrautz and @bontibon voiced preference for GitHub as a single source for our public repos, and hence, Travis CI as a preferable integration.
I have nothing prepared for Travis, only made it running for GitLab, so I'm resigning from this.

**Comment by actown** [comment]
I have a somewhat working Jenkins job currently within my own Jenkins. Any objections to using Jenkins for deployment? This blocks #34.

**Comment by Kissaki** [comment]
We currently have a closed, private Jenkins environment we could use. However, as that is not accessible from outside, it currently only runs jobs we manually trigger.

So if we want to build merge request builds/checks we don't have a Jenkins instance that could do that. We could split the infrastructure and add additional public ones, like Travis CI or Azure Pipelines, like we do for our server and client. But I think if possible one job to fit them all would be preferable.

We have been looking at Azure Pipelines as a possible alternative. They provide free builds for open source projects.

It may be viable to look at Azure Pipelines and their secrets handling, and see if we can set that up adequately.

**Comment by Kissaki** [comment]
We don’t need automatic deployment for the release, which we need to push out.

We also have more options now. GitHub actions or Azure Pipelines may also be used instead of GitLab or Travis.
